/**
 * Claim page for recipients to claim messages without a wallet
 * Requirements: 6.6
 *
 * This page is accessible via claim links generated by senders.
 * Recipients enter a passphrase to decrypt and claim their message.
 */

"use client";

import { use } from "react";
import dynamic from "next/dynamic";
import type { DecryptedRedeemPackage } from "@/types/redeem";

// Dynamic import for code splitting
const ClaimInterface = dynamic(
  () => import("@/components/redeem").then((mod) => ({ default: mod.ClaimInterface })),
  {
    loading: () => (
      <div className="flex h-64 items-center justify-center">
        <div className="text-center">
          <div className="mx-auto h-12 w-12 animate-spin rounded-full border-b-2 border-blue-600"></div>
          <p className="mt-4 text-gray-600">Loading claim interface...</p>
        </div>
      </div>
    ),
    ssr: false,
  }
);

interface ClaimPageProps {
  params: Promise<{
    packageCID: string;
  }>;
}

export default function ClaimPage({ params }: ClaimPageProps) {
  const { packageCID } = use(params);

  const handleClaimed = (redeemPackage: DecryptedRedeemPackage) => {
    // Store the claimed package info in localStorage for the dashboard
    try {
      const claimedMessages = JSON.parse(
        localStorage.getItem("claimedMessages") || "[]"
      );

      claimedMessages.push({
        packageCID,
        encryptedKeyCID: redeemPackage.encryptedKeyCID,
        encryptedMessageCID: redeemPackage.encryptedMessageCID,
        messageHash: redeemPackage.messageHash,
        unlockTimestamp: redeemPackage.unlockTimestamp,
        sender: redeemPackage.sender,
        claimedAt: Date.now(),
      });

      localStorage.setItem("claimedMessages", JSON.stringify(claimedMessages));
    } catch (err) {
      console.error("Failed to save claimed message:", err);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 px-4 py-12">
      <div className="mx-auto max-w-4xl">
        {/* Header */}
        <div className="mb-8 text-center">
          <h1 className="mb-2 text-4xl font-bold text-gray-900">Lockdrop</h1>
          <p className="text-gray-600">Guaranteed by math, not corporations</p>
        </div>

        {/* Claim Interface */}
        <ClaimInterface packageCID={packageCID} onClaimed={handleClaimed} />

        {/* Info Section */}
        <div className="mt-8 text-center text-sm text-gray-500">
          <p>Lockdrop uses client-side encryption and blockchain technology</p>
          <p>to ensure your messages remain private and time-locked.</p>
        </div>
      </div>
    </div>
  );
}
